apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: {{ template "ecr-credential-updater.fullname" . }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    {{- include "ecr-credential-updater.job" . | indent 4 }}
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 1
  suspend: false